#include "CookieJar.h"
#include <QFile>
#include <QFileInfo>
#include <QDir>
#include <QTextStream>
#include <QStringList>
#include <QRegularExpression>

namespace poppy::core {

bool CookieJar::parseNetscapeLine(const QString& rawLine, Cookie* outCookie) {
    if (!outCookie) return false;
    QString line = rawLine.trimmed();
    if (line.isEmpty()) return false;

    bool isHttpOnly = false;
    if (line.startsWith("#HttpOnly_")) {
        isHttpOnly = true;
        line = line.mid(10); // Strip '#HttpOnly_'
    } else if (line.startsWith("#")) {
        return false; // Comment line
    }

    QStringList parts = line.split('\t');
    if (parts.size() < 7) {
        // Fallback: split by multiple spaces or single tab if malformed
        parts = line.split(QRegularExpression("\\s+"));
        if (parts.size() < 7) return false;
    }

    outCookie->domain = parts[0].trimmed();
    outCookie->includeSubdomains = (parts[1].trimmed().compare("TRUE", Qt::CaseInsensitive) == 0);
    outCookie->path = parts[2].trimmed();
    outCookie->secure = (parts[3].trimmed().compare("TRUE", Qt::CaseInsensitive) == 0);
    outCookie->expires = parts[4].trimmed().toLongLong();
    outCookie->name = parts[5].trimmed();
    // Value might contain spaces if split by regex, take the rest
    if (parts.size() > 7) {
        QStringList valParts;
        for (int i = 6; i < parts.size(); ++i) valParts << parts[i];
        outCookie->value = valParts.join(" ");
    } else {
        outCookie->value = parts[6].trimmed();
    }
    outCookie->httpOnly = isHttpOnly;

    return !outCookie->name.isEmpty();
}

QString CookieJar::formatNetscapeLine(const Cookie& cookie) {
    QString line;
    if (cookie.httpOnly) {
        line += "#HttpOnly_";
    }
    line += cookie.domain;
    line += "\t";
    line += cookie.includeSubdomains ? "TRUE" : "FALSE";
    line += "\t";
    line += cookie.path.isEmpty() ? "/" : cookie.path;
    line += "\t";
    line += cookie.secure ? "TRUE" : "FALSE";
    line += "\t";
    line += QString::number(cookie.expires);
    line += "\t";
    line += cookie.name;
    line += "\t";
    line += cookie.value;
    return line;
}

bool CookieJar::loadFromFile(const QString& filePath) {
    m_cookies.clear();
    QFile file(filePath);
    if (!file.exists()) {
        return false;
    }
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine();
        Cookie c;
        if (parseNetscapeLine(line, &c)) {
            m_cookies.append(c);
        }
    }
    return true;
}

bool CookieJar::saveToFile(const QString& filePath) const {
    QFileInfo info(filePath);
    QDir dir = info.dir();
    if (!dir.exists()) {
        dir.mkpath(".");
    }

    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    out << "# Netscape HTTP Cookie File\n";
    out << "# https://curl.se/docs/http-cookies.html\n";
    out << "# This file was generated by Poppy! Edit at your own risk.\n\n";

    for (const auto& c : m_cookies) {
        out << formatNetscapeLine(c) << "\n";
    }
    return true;
}

QList<Cookie> CookieJar::cookiesForDomain(const QString& domain) const {
    QList<Cookie> result;
    QString cleanDomain = domain.trimmed();
    if (cleanDomain.startsWith(".")) cleanDomain = cleanDomain.mid(1);

    for (const auto& c : m_cookies) {
        QString cDom = c.domain;
        if (cDom.startsWith(".")) cDom = cDom.mid(1);
        if (cDom.compare(cleanDomain, Qt::CaseInsensitive) == 0 ||
            (c.includeSubdomains && cleanDomain.endsWith(cDom, Qt::CaseInsensitive))) {
            result.append(c);
        }
    }
    return result;
}

void CookieJar::addOrUpdateCookie(const Cookie& cookie) {
    for (int i = 0; i < m_cookies.size(); ++i) {
        if (m_cookies[i].domain.compare(cookie.domain, Qt::CaseInsensitive) == 0 &&
            m_cookies[i].path == cookie.path &&
            m_cookies[i].name == cookie.name) {
            m_cookies[i] = cookie;
            return;
        }
    }
    m_cookies.append(cookie);
}

bool CookieJar::removeCookie(const QString& domain, const QString& path, const QString& name) {
    for (int i = 0; i < m_cookies.size(); ++i) {
        if (m_cookies[i].domain.compare(domain, Qt::CaseInsensitive) == 0 &&
            m_cookies[i].path == path &&
            m_cookies[i].name == name) {
            m_cookies.removeAt(i);
            return true;
        }
    }
    return false;
}

void CookieJar::clear() {
    m_cookies.clear();
}

void CookieJar::clearDomain(const QString& domain) {
    QString cleanDomain = domain.trimmed();
    if (cleanDomain.startsWith(".")) cleanDomain = cleanDomain.mid(1);

    for (int i = m_cookies.size() - 1; i >= 0; --i) {
        QString cDom = m_cookies[i].domain;
        if (cDom.startsWith(".")) cDom = cDom.mid(1);
        if (cDom.compare(cleanDomain, Qt::CaseInsensitive) == 0) {
            m_cookies.removeAt(i);
        }
    }
}

} // namespace poppy::core
